### ISSUE TITLE
Play Bar

### ISSUE THREAD

**Issue by Bad-ri** [AndriaSalah/MusicPlayer-web#3]
# The row with the four buttons on the song page is too close to the screen's bottom.

![Screenshot 2022-09-27 072031](https://user-images.githubusercontent.com/74131474/192439095-88b5883e-8495-4dfa-b458-be9bf358f17d.png)

**Comment by AndriaSalah** [comment]
there was a forgotten margin which is now removed and i hope that will fix the issue , feel free to submit another issue if it's still there
