### ISSUE TITLE
Volume_Button

### ISSUE THREAD

**Issue by Bad-ri** [AndriaSalah/MusicPlayer-web#5]
Bug ID -: 1

Bug Overview -:
when the user wants to adjust the volume, if he/she clicks on the volume button and then adjusts the volume, and then clicks again on the volume button the container of the volume will loop appear and disappear without stopping, even after clicking again on the volume button.

Environment -: 
1) Device: Dell laptop
2) OS: Windows 10
3) Edge Browser

Bug Steps -:
1) Open the website
2) Choose the song
3) Click on the play button
4) Click on the volume button
5) Adjust the volume
6) Click on the volume button

Expected -:
Volume change

Actual -:
bug appears

Bug Tracking -:
1) Priority: High

**Comment by AndriaSalah** [comment]
thank you for reporting this bug , it's fixed now and will be merged soon
