### ISSUE TITLE
Shuffle_Button

### ISSUE THREAD

**Issue by Bad-ri** [AndriaSalah/MusicPlayer-web#6]
Bug ID -: 2

Bug Overview -:
when the user wants to shuffle the playlist if he/she clicks on the shuffle button and then clicks on the right/left button to change the song then nothing happens.

Environment -: 
1) Device: Dell laptop
2) OS: Windows 10
3) Edge Browser

Bug Steps -:
1) Open the website
2) Choose the song
3) Click on the play button
4) Click on the shuffle button
5) Click on the right/left button

Expected -:
play the next song

Actual -:
nothing happens

Bug Tracking -:
1) Priority: High

**Comment by AndriaSalah** [comment]
issue is now fixed thanks for reporting
