### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by Bad-ri** [AndriaSalah/MusicPlayer-web#7]
Bug ID -: 3

Bug Overview -:
when the user plays a song in any playlist and then wants to play another song from another playlist if he/she clicked on the desired playlist and clicks on the first song in this playlist it will not open and the old song will stop playing.

Environment -: 
1) Device: Dell laptop
2) OS: Windows 10
3) Edge Browser

Bug Steps -:
1) Open the website
2) Choose the song and play it
3) Choose a playlist and click on it
4) click on the first song

Expected -:
play the song

Actual -:
the old song stoped

Bug Tracking -:
1) Priority: High

**Comment by AndriaSalah** [comment]
issue is fixed now , thanks for reporting
